name: Laravel Pull Request Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9
        env:
          MYSQL_DATABASE: laravel_modular_kit
          MYSQL_USER: root
          MYSQL_PASSWORD: 
          MYSQL_ROOT_PASSWORD: 
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql, gd
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run PHPUnit tests
        run: php artisan test --stop-on-failure
